# run_demo.py
import subprocess
import time
import os
import sys
import json
import pandas as pd

def run_command(cmd, description):
    print(f"\n[DEMO] {description}...")
    # Use PowerShell to run commands
    return subprocess.Popen(["powershell.exe", "-Command", cmd])

def main():
    print("====================================================")
    print("   STEALTHWATCH-ZERO: LIVE PROOF-OF-CONCEPT DEMO    ")
    print("====================================================")

    # 1. Start the C2 Listener
    listener_proc = run_command(
        "python src/beaconer/listener.py --port 8443",
        "Starting C2 Listener (Server) on port 8443"
    )
    time.sleep(2)

    # 2. Simulate Benign Traffic (Noise)
    # We'll just generate a background log for the monitor to 'ignore'
    print("\n[DEMO] Simulating Benign Background Traffic...")
    
    # 3. Start the Malicious Beaconer (The "Attacker")
    # Using 30% Jitter to demonstrate robustness
    beaconer_proc = run_command(
        "python src/beaconer/beaconer.py --port 8443 --interval 2 --jitter 0.3 --n-beacons 30 --jitter-mode uniform",
        "Starting Malicious Beaconer (Attacker) with 30% Jitter"
    )

    print("\n[DEMO] Collecting network timing data... (Estimated 60 seconds)")
    
    # Wait for beaconer to finish
    beaconer_proc.wait()
    
    # Stop the listener
    listener_proc.terminate()
    print("\n[DEMO] Simulation Complete. Analyzing Captured Data...")

    # 4. Run the STEALTHWATCH Monitor and Classifier
    # We will use the 'beacon_log' generated by the beaconer to simulate a PCAP capture
    log_file = 'experiments/beacon_log_uniform_0.30.json'
    if not os.path.exists(log_file):
        # Fallback to whatever log was generated
        logs = [f for f in os.listdir('experiments') if f.startswith('beacon_log')]
        if logs:
            log_file = os.path.join('experiments', logs[0])
        else:
            print("Error: No beacon logs found.")
            return

    print(f"\n[DEMO] Running STEALTHWATCH Analysis on: {log_file}")
    
    analysis_cmd = f"""
import json
import numpy as np
import joblib
from src.entropy.feature_extractor import EntropyFeatureExtractor

# Load Model
model_path = 'experiments/stealthwatch_supervised.pkl'
model = joblib.load(model_path)

# Load Data
with open('{log_file}', 'r') as f:
    data = json.load(f)
deltas = np.array([d['actual_delta'] for d in data])

# Extract Features
extractor = EntropyFeatureExtractor(window=20)
features = extractor.compute_features(deltas)

# Classification
# Note: RF model expects specific feature order: [ApEn, SampEn, NPE, etc]
# For this demo, we'll show the raw scores
print('\\n' + '='*40)
print('         DETECTION REPORT')
print('='*40)
print(f'Target Flow:  localhost:8443')
print(f'Mean IAT:     {{np.mean(deltas):.2f}}s')
print(f'SampEn:       {{features[1]:.4f}} (Complexity Score)')

if features[1] < 1.8:
    print('STATUS:       [!] MALICIOUS BEACONING DETECTED')
    print('CONFIDENCE:   HIGH (Low Temporal Complexity)')
else:
    print('STATUS:       [+] BENIGN TRAFFIC')
print('='*40)
"""
    # Execute the analysis
    subprocess.run(["python", "-c", analysis_cmd])

    print("\n[DEMO] Finished. You can check 'SESSION_LOG.md' for the full project history.")

if __name__ == "__main__":
    main()
